### ISSUE TITLE
`sserver` cli-shortcut

### ISSUE THREAD

**Issue by iamstarkov** [nbluis/static-server#13]
can we add `sserver` cli-shortcut? it’s easier to type, and can be easily autocompleted.

**Comment by yanickrochon** [comment]
Can you provide more information? There is no console with this project...

**Comment by iamstarkov** [comment]
Readme states another: 

> Run the server `static-server`

And I want to run it with `sserver` instead of not-type-friendly `static-server`

**Comment by nbluis** [comment]
Well, you van just add an alias on bashrc no ?

alias sserver='static-server'
Em 04/05/2015 11:49, "Vladimir Starkov" <notifications@github.com> escreveu:

**Comment by yanickrochon** [comment]
Yes, I was about to suggest that, too :)

I suggest we leave this open and see if others speak out about this. I personally don't mind `static-server` as it autocompletes just fine under Ubuntu.

**Comment by iamstarkov** [comment]
OS X with zsh autcomplete not working well in this case, and I had this proplem year ago and since that time, nothing change. That’s why I wanted to discuss it with you

**Comment by yanickrochon** [comment]
@iamstarkov take a look at this [SO question](http://stackoverflow.com/questions/415403/whats-the-difference-between-bashrc-bash-profile-and-environment) and edit the appropriate file to add your alias.

**Comment by iamstarkov** [comment]
@yanickrochon i’m fine with unix workflow, but if it is permanent issue not only for me, then maybe point of change should not my workflow, but in package itself

**Comment by yanickrochon** [comment]
As I said, I suggest we leave this open for others to comment :)

**Comment by iamstarkov** [comment]
Sure, it makes. thank you

**Comment by iamstarkov** [comment]
prob its time and to close this issue
