### ISSUE TITLE
Upgrade to Node 4 and 5

### ISSUE THREAD

**Issue by yanickrochon** [nbluis/static-server#16]
... and drop support for Node 0.10, 0.11, and 0.12.
- [ ] Update tests to support `let` and `const` and all compatible ES5/6 commonly implemented features
- [ ] Make the server class based
- [ ] Use `Promise` instead of callbacks to support future `async/await`

**Comment by nbluis** [comment]
Hi guys, thanks a lot for your help.

I decided to retire the project as I no longer have the time to maintain it.

If any of you are interested in making a fork, I'd be happy to mention it for others in the community to use.

More information about this in the README.
