### ISSUE TITLE
Optional Browser

### ISSUE THREAD

**Issue by pranayreddi** [nbluis/static-server#26]
Hi,

How can I use the optional browser like Phantom.js? Can you please let me know.

Thanks.

**Comment by nbluis** [comment]
Hi @pranayreddi.

Maybe I did not understand your need.

But static-server does not validate or maintain any specific behavior for browsers.

A program that uses PhantonJs and requests a url for static-server, will receive the response normally like any other browser.

Static-server currently has no goal of having any client-side relationship, just to serve static files locally in a simplified way.

I hope I have helped :smiley: :smiley: :smiley:

**Comment by nbluis** [comment]
I'll close this issue for now.
