### ISSUE TITLE
Enabling Clean URLs

### ISSUE THREAD

**Issue by wamoyo** [nbluis/static-server#27]
It would be nice to be able to serve clean URLs for static sites. For example, an HTML file without the .html extension is treated like an octet-string content type. This prompts the browser to download the file instead of loading it as html.

**Comment by nbluis** [comment]
Hi, thanks for the suggestion.

Can you explain better how you would use this?

I think that implementing this way could generate problems because there may be files without extension and in case of duplication the software would have to decide which one to use.

Maybe a url parameter `http://host/file.html?download` makes sense?

**Comment by wamoyo** [comment]
I can definitely give you my case, and I'd happily chime in on other use cases, but I probably have a less diverse view of the possible contexts and use cases than you do. 

### My Case

I push my static files up to S3 with CloudFront as a CDN. On S3, I have an index.html, and index file with no extension. The two files are identical. Same goes for about.html and about, 404.html and 404 and so forth. (404 is my error page). On S3, there is a content-type header option which I set to 'text/html' for the files without extensions. This allows CloudFront to server the clean URL out of S3. example.com/about returns the about file without the extension, but with content-type set to 'text/html'. Also, example.com/about.html returns the same content through a different file, just in case someone types out the extension. Everyone's happy. 

On my localhost, I run a git hook pre-push in order to copy up and changes, I then also loop through the html files and check if there are any diffs between them and their counterparts which don't have the .html extension. Compare index.html to index, about.html to about, and so on. If there is a change, it means I've updated the file, and so I copy the file up to S3 with a content-type option set to html. 

The challenge is serving up my local content. All my hrefs point to clean URLs, and they all prompt a download. Oddly enough, that behavior is totally new. Everything was working fine. The prompt to download showed up quite randomly this afternoon, sending me into the dependency bowels of my node_modules, ending here : ) Hi! How's it goin'?

**Comment by wamoyo** [comment]
@nbluis I've found another way to do this that might be very easy to implement in this project.

http-server (https://www.npmjs.com/package/http-server) has an interesting fallback. If you request example.com/about without the .html, and there isn't a file called 'about', but there is one called 'about.html' it will use that one. 

If there were a similar fallback option that would enable clean URLs.

**Comment by Rawphs** [comment]
Hi! Did this ever get implemented? I'd like a fallback as well.

**Comment by nbluis** [comment]
Hi guys, thanks a lot for your help.

I decided to retire the project as I no longer have the time to maintain it.

If any of you are interested in making a fork, I'd be happy to mention it for others in the community to use.

More information about this in the README.
