### ISSUE TITLE
--no-cache option

### ISSUE THREAD

**Issue by mendrik** [nbluis/static-server#28]
would be nice for local developments to force no-cache/expired headers on all files. right now my mobile phone caches the resources to aggressively

**Comment by nbluis** [comment]
Hmmm, makes sense.

Would you like to try to implement and send a pull request?

**Comment by mendrik** [comment]
I'll look into it

**Comment by lorenmh** [comment]
@nbluis I was also encountering this issue (using static-server for development). Just submitted a pull request #32 which adds a `--no-cache` flag which returns the file with a 200. It doesn't modify the ETag value though

**Comment by karolk** [comment]
@nbluis this option is also incorrectly documented on the npm page: https://www.npmjs.com/package/static-server (states `--no-nocache` instead of `--no-cache`)
