### ISSUE TITLE
Response object is null

### ISSUE THREAD

**Issue by lkostrowski** [nbluis/static-server#34]
Node: 9.4

```
server.on('request', function (req, res) {
  // req.path is the URL resource (file name) from server.rootPath
  // req.elapsedTime returns a string of the request's elapsed time
});
```

In this case `res` is null, so you can't modify f.e headers (I needed to add MIME)

For new node version I suggest [node-static](https://www.npmjs.com/package/node-static)

I suggest to just write compatible node versions to readme

**Comment by alaa-eddine** [comment]
I also got the same error, seems like a small mistake or copy/past issue, here is a PR to fix it.
