### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by trungdq88** [nbluis/static-server#36]
![image](https://user-images.githubusercontent.com/4214509/36639541-4419b39a-1a41-11e8-96a0-3659710249a1.png)

<img width="627" alt="tmux_new_-s___basename___pwd____tmux_" src="https://user-images.githubusercontent.com/4214509/36639566-c984cc54-1a41-11e8-8116-a87cce3d1611.png">

**Comment by nbluis** [comment]
Ohhh. I see it. Thanks for your reporting.

The `port` parameter is not optional when used as a module.

I'll adjust this in readme.

**Comment by trungdq88** [comment]
Why not make it optional?

**Comment by nbluis** [comment]
Well, it can be optional but not using a random port because this cause some problems.

Would you like to send a pr with this?

**Comment by nbluis** [comment]
Hi guys, thanks a lot for your help.

I decided to retire the project as I no longer have the time to maintain it.

If any of you are interested in making a fork, I'd be happy to mention it for others in the community to use.

More information about this in the README.
