### ISSUE TITLE
The template notFound does not use the rootPath like index does

### ISSUE THREAD

**Issue by mpardue** [nbluis/static-server#39]
For the rootPath to have a value, I have to concatenate the same value to notFound

If I configure the server like the following, it will return 403 forbidden's because the path will not be accessible.
```
{
  rootPath: './build',
  templates: {
    index: 'index.html',
    notFound: 'index.html'
  }
}
```

I have to configure it like so for it to work:
```
{
  rootPath: './build',
  templates: {
    index: 'index.html',
    notFound: 'build/index.html'
  }
}
```

**Comment by eduardor2k** [comment]
First of all, thanks! I did not know, why my error page wasn't working.

In my case:

    var server = new StaticServer({
        rootPath: baseDir,            // required, the root of the server file tree
        port: 3000,
        templates: {
            index: 'index.html',      // optional, defaults to 'index.html'
            notFound: baseDir+'/index.html'    // optional, defaults to undefined
        }
    });

Hope it helps other users

**Comment by nbluis** [comment]
Hi guys, thanks a lot for your help.

I decided to retire the project as I no longer have the time to maintain it.

If any of you are interested in making a fork, I'd be happy to mention it for others in the community to use.

More information about this in the README.
