### ISSUE TITLE
CORS works incorrectly 

### ISSUE THREAD

**Issue by reuwi** [nbluis/static-server#40]
In my laptop, I use ```-c *``` and everything works ok, but in my cloud server, I use the same command line, the Access-Control-Allow-Origin in response headers is wrong. 

My cloud server system is Ubuntu, and node version is 8.11.1, npm version 5.6.0

**Comment by nbluis** [comment]
Hi guys, thanks a lot for your help.

I decided to retire the project as I no longer have the time to maintain it.

If any of you are interested in making a fork, I'd be happy to mention it for others in the community to use.

More information about this in the README.
