### ISSUE TITLE
Silence output

### ISSUE THREAD

**Issue by mathiasrw** [nbluis/static-server#44]
Would you be willing to accept a PR for a flag that will suppress the output of what URLs being fetched?

**Comment by nbluis** [comment]
I think so, seems interesting.

**Comment by mathiasrw** [comment]
I have added https://github.com/nbluis/static-server/pull/45 to solve this.

**Comment by nbluis** [comment]
Hi guys, thanks a lot for your help.

I decided to retire the project as I no longer have the time to maintain it.

If any of you are interested in making a fork, I'd be happy to mention it for others in the community to use.

More information about this in the README.
