### ISSUE TITLE
Doesn't listen IPV6 [::1]

### ISSUE THREAD

**Issue by PavelSosin** [nbluis/static-server#48]
I succeeded to start static-http-server in Windows 10 Linux subsystem Ubuntu 18.06 with fresh- installed nodejs 12.3.1 Server starts and displays port list
Expected: since I'm in IPV6 network both at home and at office, I expect local IPV6 address [::1] like in PING localhost(localhost (::1)) 56 data bytes
Actual: list of irrelevant IPV4 addresses.
Proposed solution: Nodejs supports IPV6 Please, correct static-http-server according nodejs documentation
Chrome and Edge default on Windows 10 is IPV6

**Comment by PavelSosin** [comment]
It looks like express has the similar problem: [express issue](https://github.com/expressjs/express/issues/3528)
The node's default now is IPV6. Back compatibility mode requires additional parameter in listen. Google prefers default IPV6. Me too

**Comment by PavelSosin** [comment]
It looks like 
    _### server.listen(config.port, function() {
        if (!nolog) {
            console.log(banner);
        }
        callback(null, server);
    });
i_s insufficient now. It is recommended now to use explicit [::1] but I didn't check it yet

**Comment by nbluis** [comment]
Hi guys, thanks a lot for your help.

I decided to retire the project as I no longer have the time to maintain it.

If any of you are interested in making a fork, I'd be happy to mention it for others in the community to use.

More information about this in the README.
