### ISSUE TITLE
CLI displays warning: options.index is now deprecated

### ISSUE THREAD

**Issue by corwin-of-amber** [nbluis/static-server#52]
This always shows when running `bin/static-server.js`:
```
options.index is now deprecated please use options.templates.index instead.
```

A possible fix would be to add `program.index = undefined;` after:
https://github.com/nbluis/static-server/blob/ab1ca098e371d249d6f34b0b03ba16760b8596e1/bin/static-server.js#L44

Since `program` (command line options object) is passed as `options` to the constructor.

**Comment by nbluis** [comment]
Hi guys, thanks a lot for your help.

I decided to retire the project as I no longer have the time to maintain it.

If any of you are interested in making a fork, I'd be happy to mention it for others in the community to use.

More information about this in the README.
