### ISSUE TITLE
Not working with gulp 4

### ISSUE THREAD

**Issue by moatefdev** [nbluis/static-server#55]
When I install this package to use it with gulp.js, it actually doesn't work although I didn't find any errors or warnings and the path is right. So, why it doesn't work for me? Is it compatible with gulp 4?

**Comment by nbluis** [comment]
Hi guys, thanks a lot for your help.

I decided to retire the project as I no longer have the time to maintain it.

If any of you are interested in making a fork, I'd be happy to mention it for others in the community to use.

More information about this in the README.
