### ISSUE TITLE
Create an option to start server with directory listing

### ISSUE THREAD

**Issue by nbluis** [nbluis/static-server#6]
Directory listing (like apache) is a good feature sometimes we have a directory with a lot of files.

When asked for a directory, instead of opening the default file (index.html), list all files and directories within it.

I think a html page to link each entry is a good idea.

PS: Just to be safe, should only be enabled via parameter not by default.

**Comment by pconerly** [comment]
+1 this would be awesome.

**Comment by pconerly** [comment]
If you haven't started on this, would you accept a pull request for it?  I might write it out real quick.

**Comment by yanickrochon** [comment]
If you want to contribute, your PR should include these changes 

1. command-line argument information (ex: `-l, --directory-listing`)
2. `StaticServer` constructor `options` documentation and instance property (ex: `this.directoryListing = true;`)
3. Wrap current [check](https://github.com/nbluis/static-server/blob/master/server.js#L147) in an `IF` block, checking the option
4. Implement the function.

Optionally, the renderer could also be a delegated function defaulting to a very basic directory listing renderer. For example :

```
server.directoryListingRenderer(req, res, file, stat);
```

This way, when used as a third party module, a function may be given to format the output to a predefined format.

My2cents

**Comment by nbluis** [comment]
Hello @pconerly.

Sorry about the delay, was on vacation in the last days. :satisfied:

It will be great if you want to contribute. If you want to start implementation and ask for feedback before the pulll-request I will be happy to help.

Try to start the implementation using the tests to simplify validation and regression.

The tips above are great @yanickrochon, thank you.

Att;

**Comment by nbluis** [comment]
Hi guys, thanks a lot for your help.

I decided to retire the project as I no longer have the time to maintain it.

If any of you are interested in making a fork, I'd be happy to mention it for others in the community to use.

More information about this in the README.
